# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(597, 464)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 591, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 151, 31))
        self.comboBox.setObjectName("comboBox")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(20, 240, 401, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.send = QtWidgets.QPushButton(self.tab)
        self.send.setGeometry(QtCore.QRect(430, 240, 61, 41))
        self.send.setObjectName("send")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(20, 51, 401, 181))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.myFriends = QtWidgets.QListWidget(self.tab_2)
        self.myFriends.setGeometry(QtCore.QRect(10, 60, 171, 261))
        self.myFriends.setObjectName("myFriends")
        self.kisiler = QtWidgets.QListWidget(self.tab_2)
        self.kisiler.setGeometry(QtCore.QRect(340, 60, 171, 261))
        self.kisiler.setObjectName("kisiler")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(50, 30, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(380, 30, 71, 21))
        self.label_2.setObjectName("label_2")
        self.addFriends = QtWidgets.QPushButton(self.tab_2)
        self.addFriends.setGeometry(QtCore.QRect(190, 130, 141, 41))
        self.addFriends.setObjectName("addFriends")
        self.removeFriends = QtWidgets.QPushButton(self.tab_2)
        self.removeFriends.setGeometry(QtCore.QRect(190, 180, 141, 41))
        self.removeFriends.setObjectName("removeFriends")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 597, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.send.setText(_translate("MainWindow", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Mesaj Gönder"))
        self.label.setText(_translate("MainWindow", "Arkadaşlarım"))
        self.label_2.setText(_translate("MainWindow", "Tüm Kullanıcılar"))
        self.addFriends.setText(_translate("MainWindow", "<<< Arkadaş Ekle"))
        self.removeFriends.setText(_translate("MainWindow", "Arkadaşlıktan Çıkar >>>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Arkadaşlar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Profil"))
