# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'makro.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 463)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(40, 30, 81, 61))
        self.play.setObjectName("play")
        self.record = QtWidgets.QPushButton(self.centralwidget)
        self.record.setGeometry(QtCore.QRect(130, 30, 81, 61))
        self.record.setObjectName("record")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(220, 30, 81, 61))
        self.stop.setObjectName("stop")
        self.tablo = QtWidgets.QTableWidget(self.centralwidget)
        self.tablo.setGeometry(QtCore.QRect(40, 130, 521, 281))
        self.tablo.setColumnCount(4)
        self.tablo.setObjectName("tablo")
        self.tablo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(3, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 605, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play.setText(_translate("MainWindow", "Çalıştır"))
        self.record.setText(_translate("MainWindow", "Kaydı Başlat"))
        self.stop.setText(_translate("MainWindow", "Durdur"))
        item = self.tablo.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "İşlem id"))
        item = self.tablo.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Eylem"))
        item = self.tablo.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Değer"))
        item = self.tablo.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Açıklama"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
